name: C/C++ CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2022
  
    steps: 
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Checkout repositories
      uses: ./.github/checkout_repos

    - name: Build server
      run: |
        mkdir build
        cd build
        cmake ..  -A Win32 -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=OFF
        cmake --build . --config Release

    - name: Build plugins
      run: |
        cd build
        cmake ..  -A Win32 -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=ON
        cmake --build . --config Release

    - name: Build client
      run: |
        cd build
        cmake ..  -A Win32 -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF -DBUILD_PLUGINS=OFF
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sevenkewp-windows
        path: build/output/

  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Checkout repositories
      uses: ./.github/checkout_repos
    
    - name: Download and install dependencies
      run: |
        sudo apt update
        sudo apt install gcc-multilib g++-multilib libc6-dev-i386

    - name: Build server
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=OFF
        cmake --build .

    - name: Build plugins
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=ON
        cmake --build .

    - name: Build client
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF -DBUILD_PLUGINS=OFF
        cmake --build .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sevenkewp-linux
        path: build/output/
